[project]
channels = ["conda-forge"]
description = "Add a short description here"
name = "gaussian_splatting"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
postinstall = "pip install --no-build-isolation --no-deps --disable-pip-version-check submodules/diff-gaussian-rasterization submodules/fused-ssim"

[system-requirements]
cuda = "12.4"

[dependencies]
python = "3.12.*"
pip = "*"
pytorch-gpu = "2.4.1.*"
cuda-version = "12.4.*"
torchvision = "*"
plyfile = "*"
tqdm = "*"
ninja = "*"
scipy = "*"

[pypi-dependencies]
opencv-python = "*"
joblib = "*"
setuptools = "*"
