[project]
authors = ["Michal Černý <33428111+cernymichal@users.noreply.github.com>"]
channels = ["pytorch", "nvidia", "conda-forge"]
description = "Add a short description here"
name = "gaussian_splatting"
platforms = ["win-64", "linux-64"]
version = "0.1.0"

[tasks]
postinstall = "pip install --no-build-isolation --no-deps --disable-pip-version-check submodules/diff-gaussian-rasterization submodules/simple-knn submodules/fused-ssim"

[system-requirements]
cuda = "12.1"

[dependencies]
python = "3.8.*"
pip = "*"
pytorch = "2.1.1.*"
pytorch-cuda = "12.1.*"
cuda = "12.1.*"
cuda-version = "12.1"
torchaudio = "*"
torchvision = "*"
plyfile = "*"
tqdm = "*"
ninja = "*"

[pypi-dependencies]
opencv-python = "*"
joblib = "*"
setuptools = "*"
